name: Docker Build & Release

on:
    workflow_dispatch:
    push:
      tags:
        - 'v*.*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
              with:
                platforms: arm64
            - name: 'Login to GitHub Container Registry'
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_TOKEN}}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                driver-opts: image=moby/buildkit:latest
            - name: Build and push PHP-8.3
              uses: docker/build-push-action@v5
              with:
                  registry: docker.io
                  image: effiana/unit
                  directory: .
                  file: unit/alpine-8.3/Dockerfile
                  platforms: linux/amd64,linux/arm64
                  enableBuildKit: true
                  multiPlatform: true
                  overrideDriver: true
                  addLatest: true
                  pushImage: true
                  push: true
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  tags: |
                    effiana/unit:${{ github.sha }}
                    effiana/unit:php8.3-alpine